# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .Net

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  PATH_PROJECT_API: ./TimeTrackerBack/app
  PATH_PROJECT_API_TEST: ./TimeTrackerBack/app.Tests

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Restore Dependencies
        run: dotnet restore ${{ env.PATH_PROJECT_API }}

      - name: Build API
        run: dotnet build ${{ env.PATH_PROJECT_API }} -c Release --no-restore

      - name: Run Tests
        run: dotnet test --no-build ${{ env.PATH_PROJECT_API_TEST }} --verbosity normal

  deploy-dev:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Deploy to Development Environment
        run: echo "Deploying to Development Environment"
